source_mapping = {
    "data/iss1.pdf": "https://www.buffalo.edu/international-student-services/immigration-visa/f-1-student/immigration-documents.html",
    "data/iss2.pdf": "https://www.buffalo.edu/international-student-services/immigration-visa/f-1-student/sevis-fee.html",
    "data/iss3.pdf": "https://www.buffalo.edu/international-student-services/immigration-visa/f-1-student/maintaining-f-1-student-status.html",
    "data/iss4.pdf": "https://www.buffalo.edu/international-student-services/immigration-visa/f-1-student/on-campus-employment.html",
    "data/iss5.pdf": "https://www.buffalo.edu/international-student-services/immigration-visa/f-1-student/reduced-course-load.html",
    "data/iss6.pdf": "https://www.buffalo.edu/international-student-services/immigration-visa/f-1-student/reduced-course-load/academic-difficulty-reduced-course-load.html",
    "data/iss7.pdf": "https://www.buffalo.edu/international-student-services/immigration-visa/f-1-student/reduced-course-load/final-semester-reduced-course-load.html",
    "data/iss8.pdf": "https://www.buffalo.edu/international-student-services/immigration-visa/f-1-student/reduced-course-load/medical-condition-reduced-course-load.html",
    "data/iss9.pdf": "https://www.buffalo.edu/international-student-services/immigration-visa/f-1-student/extension-of-stay.html",
    "data/iss10.pdf": "https://www.buffalo.edu/international-student-services/immigration-visa/f-1-student/extension-of-stay.html",
    "data/iss11.pdf": "https://www.buffalo.edu/international-student-services/immigration-visa/f-1-student/leave-of-absence/requesting-a-leave-of-absence.html",
    "data/iss12.pdf": "https://www.buffalo.edu/international-student-services/immigration-visa/f-1-student/leave-of-absence/returning-from-a-leave-of-absence.html",
    "data/iss13.pdf": "https://www.buffalo.edu/international-student-services/immigration-visa/f-1-student/curricular-practical-training--cpt-.html",
    "data/iss14.pdf": "https://www.buffalo.edu/international-student-services/immigration-visa/f-1-student/optional-practical-training--opt-/pre-completion-opt.html",
    "data/iss15.pdf": "https://www.buffalo.edu/international-student-services/immigration-visa/f-1-student/optional-practical-training--opt-/post-completion-opt.html",
    "data/iss16.pdf": "https://www.buffalo.edu/international-student-services/immigration-visa/f-1-student/optional-practical-training--opt-/maintaining-status-during-post-completion-opt.html",
    "data/iss17.pdf": "https://www.buffalo.edu/international-student-services/immigration-visa/f-1-student/optional-practical-training--opt-/cap-gap-extension.html",
    "data/iss18.pdf": "https://www.buffalo.edu/international-student-services/immigration-visa/f-1-student/optional-practical-training--opt-/24-month-stem-extension.html",
    "data/iss19.pdf": "https://www.buffalo.edu/international-student-services/immigration-visa/f-1-student/optional-practical-training--opt-/maintaining-status-while-on-opt.html",
    "data/iss20.pdf": "https://www.buffalo.edu/international-student-services/immigration-visa/f-1-student/adding-a-dependent.html",
    "data/iss21.pdf": "https://www.buffalo.edu/international-student-services/immigration-visa/f-1-student/ChangeofStatustoF-1.html",
    "data/iss22.pdf": "https://www.buffalo.edu/international-student-services/immigration-visa/f-1-student/reinstatement.html",
    "data/iss23.pdf": "https://www.buffalo.edu/international-student-services/immigration-visa/f-1-student/economic-hardship-work-authorization.html",
    "data/iss24.pdf": "https://www.buffalo.edu/international-student-services/immigration-visa/f-1-student/sevis-transfer.html",
    "data/iss25.pdf": "https://www.buffalo.edu/international-student-services/immigration-visa/f-1-student/leaving-ub.html",
    "data/iss26.pdf": "https://www.buffalo.edu/content/www/international-student-services/immigration-visa/f-1-student/optional-practical-training--opt-/i-765-online-pw.html"
}
